# Generated by Django 6.1.1 on 2026-09-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gate_fee',
            field=models.CharField(default='Free', max_length=50),
        ),
    ]
