# Generated by Django 6.1.1 on 2026-09-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_category_options_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='order_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
