# Generated by Django 6.1.1 on 2026-09-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_ticket_order_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
