# Generated by Django 6.1.1 on 2026-09-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_ticket_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
