# Generated by Django 6.1.1 on 2026-09-24 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer'),
        ('events', '0006_ticket_scanned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_tickets', to='accounts.customer'),
        ),
    ]
