# Generated by Django 6.1.1 on 2026-09-30 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_payoutrequest'),
        ('events', '0008_alter_event_gate_fee_alter_event_is_free_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='events.event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organizer')),
            ],
        ),
    ]
