# Generated by Django 6.1.1 on 2026-10-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_ticket_quantity_alter_ticket_order_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='hidden_by_customer',
            field=models.BooleanField(default=False),
        ),
    ]
