# Generated by Django 6.1.1 on 2026-09-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='paystack_subaccount_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
