# Generated by Django 5.2.17 on 2026-09-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organizer_paystack_subaccount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
