# Generated by Django 5.2.17 on 2026-09-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organizer_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='unverified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'unverified'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='unverified', max_length=20),
        ),
    ]
