# Generated by Django 5.2.17 on 2026-09-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organizer_unverified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='momo_network',
            field=models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('vodafone', 'Telecel Cash'), ('airteltigo', 'AirtelTigo Money')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='momo_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='paystack_subaccount_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
