# Generated by Django 5.2.17 on 2026-09-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organizer_momo_network_organizer_momo_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='is_subaccount_active',
            field=models.BooleanField(default=False),
        ),
    ]
