# Generated by Django 6.1.1 on 2026-09-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organizer_is_subaccount_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
